GET http://localhost:7999/api/insertOneStudent

###
GET http://localhost:7999/api/insertTenStudent

###
GET http://localhost:7999/api/insertNStudent/15

###


### 正式测试, 保存到数据库, 数据就是程序员的生命
POST http://localhost:7999/api/generateStatistic
Content-Type: application/json

[
  1,
  10,
  100,
  1000,
  10000,
  1000
]

### 正式测试, pack保存到数据库
POST http://localhost:7999/api/generateStatisticForeach
Content-Type: application/json

{
  "total": 1000,
  "packSize": 1000
}

###